# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HEARYE Blog
email: info@hearye.io
description: > # this means to ignore newlines until "baseurl:"
 HearYe is an iOS app that allows students to find things to do on campus, http://www.hearye.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.blog.hearye.io" # the base hostname & protocol for your site
twitter_username: hearyeapp

# Build settings
markdown: kramdown
